name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    buildImage: true
    deployService: true
    deployEnvironment: development
    imageTags: |
      $(Build.BuildId)
      develop
    frontServiceName: landing-develop_front
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    buildImage: true
    deployService: true
    deployEnvironment: production
    imageTags: |
      $(Build.BuildId)
      latest
    frontServiceName: landing_front

stages:
- stage: build
  jobs:
  - job: buildFront
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: npm ci
      inputs:
        command: 'ci'

    - task: Npm@1
      displayName: build front
      inputs:
        command: 'custom'
        customCommand: 'run buildToDeploy'

    - publish: ./deploy
      artifact: landing-build
- stage: dockerImage
  condition: ${{variables.buildImage}}
  jobs:
  - job: dockerBuild
    steps:
    - download: current
      artifact: landing-build
      displayName: Download landing-build
    - task: Docker@2
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/landing-front'
        command: 'buildAndPush'
        Dockerfile: '$(Pipeline.Workspace)/landing-build/Dockerfile'
        buildContext: '$(Pipeline.Workspace)/landing-build'
        tags: ${{variables.imageTags}}
- stage: UpdateFront
  condition: ${{variables.deployService}}
  jobs:
  - deployment: DeployFront
    pool:
      vmImage: 'ubuntu-latest'
    environment: ${{variables.deployEnvironment}}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image rtuitlab/landing-front:$(Build.BuildId) ${{variables.frontServiceName}}'
                readyTimeout: '20000'