trigger:
  - master
  - develop
name: $(BuildID)-$(Build.SourceBranchName)
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'ci'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    ArtifactName: 'itlab-landing-build'
    publishLocation: 'Container'
