# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ data ]
  pull_request:
    branches: [ data ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token 
  
    - name: checkoug Landing-Front to master
      uses: actions/checkout@v2
      with:
        repository: baikinkirill/Landing-Front
        ref: master
        path: Landing-Front
        lfs: true
        
    - run: cd ./Landing-Front && git submodule update --init --recursive -j 8
    - run: cd ./Landing-Front/data && git checkout data
    - run: cd ./Landing-Front/data && git pull
    - run: cd ./Landing-Front && git add .
    - run: cd ./Landing-Front && git commit -m "Pulled down update to data"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        path: Landing-Front
        token: ${{ secrets.GITHUB_TOKEN }}
        committer: GitHub <noreply@github.com>
        author: GitHub <noreply@github.com>
        commit-message: update information about ${{ github.repository }}
        title: Update information about ${{ github.repository }}
        branch: 'sync/master'
        delete-branch: true
  
    - run: gh pr create --title "Update data" --base master --head sync/master --body "" -a baikinkirill,ivlaptev || true
