name: Tests for LANDING.md parser 


on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    paths:
      - 'parser/**'
      - '!parser/PARSER.md'
  

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install -U pip
          pip install -r parser/requirements.txt
      - name: Run tests
        run: pytest
