# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      envPAT:
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
        
    - uses: actions/checkout@v2
    - run: git clone https://github.com/baikinkirill/Landing-Front.git
    - run: ls
    - run: cd ./Landing-Front
    - run: ./Landing-Front git checkout -b data
    - run: ls ./Landing-Front
    - run: cp ../LANDING.md ./projects/${{ github.repository }}
    - run: git add .
    - run: git commit -m "Update ${{ github.repository }} info"
    - run: git push
    - run: echo ${{ github.repository }}
