# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      envPAT:
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
        
    - uses: actions/checkout@v2
    - run: git clone https://github.com/baikinkirill/Landing-Front.git
    - run: ls
    - run: cd ./Landing-Front
    - run: cd ./Landing-Front && git switch data
    - run: export projectName=$(echo "${{ github.repository }}" | grep '[^/]*$' -o)
    - run: echo $projectName
    - run: mkdir ./Landing-Front/projects/$projectName || true
    - run: cp ./LANDING.md ./Landing-Front/projects/$projectName
    - run: ls ./Landing-Front/projects
    - run: git add .
    - run: git commit -m "Update ${{ github.repository }} info"
    - run: git push
    - run: echo ${{ github.repository }}
