# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      envPAT:
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
        
    - uses: actions/checkout@v2
    - name: Checkout static files
      uses: actions/checkout@v2
      with:
        repository: baikinkirill/Landing-Front
        ref: data
        path: Landing-Front
        lfs: true
        
    - run: git config --global user.email "bk@finebot.site"
    - run: git config --global user.name "baikinkirill"
    - run: cd ./Landing-Front
    - run: ls
    - run: cd ./Landing-Front && git switch data
    - run: mkdir ./Landing-Front/projects/$(echo "${{ github.repository }}" | grep '[^/]*$' -o) || true
    - run: echo $(echo "${{ github.repository }}" | grep '[^/]*$' -o)
    - run: cp ./LANDING.md ./Landing-Front/projects/$(echo "${{ github.repository }}" | grep '[^/]*$' -o)
    - run: cd ./Landing-Front && git add .
    - run: cd ./Landing-Front && git commit -m "Update ${{ github.repository }} info"          
    - run: ls
    - run: cd ./Landing-Front && git push
    - run: echo ${{ github.repository }}
