# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
        
    - uses: actions/checkout@v2
    - name: checkoug Landing-Front
      uses: actions/checkout@v2
      with:
        repository: baikinkirill/Landing-Front
        ref: data
        path: Landing-Front
        lfs: true
        
    #- run: printf "protocol=https\nhost=github.com\nusername=baikinkirill\npassword=${{ secrets.PAT }}" | git credential fill
  
    - run: git config --global user.email "bk@finebot.site"
    - run: git config --global user.name "baikinkirill"
    - run: mkdir ./Landing-Front/projects/$(echo "${{ github.repository }}" | grep '[^/]*$' -o) || true
    - run: cp ./LANDING.md ./Landing-Front/projects/$(echo "${{ github.repository }}" | grep '[^/]*$' -o)
    - run: cd ./Landing-Front && git add .
    - run: cd ./Landing-Front && git commit -m "Update LANDING.md"
    
    - run: echo "${{secrets.envPAT}}"
    
    - name: Pushes to another repository
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.envPAT }}
      with:
        source-directory: Landing-Front/
        destination-github-username: 'baikinkirill'
        destination-repository-name: 'Landing-Front'
        user-email: kirill.baikin@gmail.com
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
        target-branch: data
    
    
    #- run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token 
   # - run: gh pr create --title "New landing build" --base origin/data --head data --body "" -a baikinkirill
   
   
    
